// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ONW_API.Infrastructure.Data;

#nullable disable

namespace ONW_API.Migrations
{
    [DbContext(typeof(OnWayDbContext))]
    partial class OnWayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnWay.API.Domain.Entities.Transporter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Transporters", (string)null);
                });

            modelBuilder.Entity("OnWay.API.Domain.Entities.Transporter", b =>
                {
                    b.OwnsOne("OnWay.Domain.Transporters.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("TransporterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Email");

                            b1.HasKey("TransporterId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Transporters");

                            b1.WithOwner()
                                .HasForeignKey("TransporterId");
                        });

                    b.OwnsOne("OnWay.Domain.Transporters.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("TransporterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("TransporterId");

                            b1.ToTable("Transporters");

                            b1.WithOwner()
                                .HasForeignKey("TransporterId");
                        });

                    b.OwnsOne("OnWay.Domain.Transporters.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("TransporterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Phone");

                            b1.HasKey("TransporterId");

                            b1.ToTable("Transporters");

                            b1.WithOwner()
                                .HasForeignKey("TransporterId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
